### ISSUE TITLE
create subscriber that will refresh api token on authn failure

### ISSUE THREAD

**Issue by stopfstedt** [ilios/php-api-client#6]
some thoughts:

- should only process 401 errors, api token must be present.
- attempt to refresh token at `/auth/refresh`.
- should only run _once_ per request

relevant docs
http://guzzle.readthedocs.org/en/5.3/events.html?highlight=subscriber#event-subscribers
http://guzzle.readthedocs.org/en/5.3/events.html?highlight=subscriber#error

other thoughts:
- the client should have a public `refreshToken()` method in any case
- currently blocked by ilios/ilios#904

**Comment by stopfstedt** [comment]
turns out that this is not how it works.
the server will not (and should not) exchange a fresh token for an expired one.

**Comment by thecoolestguy** [comment]
https://www.youtube.com/watch?v=no0qB8CVspY
